spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/umc?serverTimezone=Asia/Seoul
    username: root
    password: dayon0325

  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


  server:
    port: 8080


